---
version: '2'
services:

  broker1:
    hostname: localhost
    container_name: broker1
    image: confluentinc/cp-server:7.6.0
    networks:
      - my-network
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      CLUSTER_ID: xtzWWN4bTjitpL3kfd9s5g
      KAFKA_LISTENERS: BROKER://:39094,EXTERNAL://:9092,CONTROLLER://:29092
      KAFKA_ADVERTISED_LISTENERS: BROKER://broker1:39094,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_PROCESS_ROLES: 'controller,broker'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:29092'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_DURABILITY_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1


      KAFKA_KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      #      KAFKA_LOG_FLUSH_INTERVAL_MS: 1000
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_QUOTAS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_KAFKA_LOG4J_ROOT_LOGLEVEL: "ERROR"
      KAFKA_LOG4J_ROOT_LOGLEVEL: "ERROR"
      KAFKA_MIN_INSYNC_REPLICAS: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - my-network
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: broker1:39094
    depends_on:
      - broker1


networks:
  my-network:
    driver: bridge